spring.application.name=core-policyinfo-service
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/policy_info
spring.datasource.username=root
spring.datasource.password=Belikeman+-2112

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

alturion.policyowner.service.url=http://localhost:8080/api/policyowners/